version: "3.8"

services:
  redis:
    image: "redis:alpine"
    command: redis-server
    restart: always
    container_name: "proj_redis"
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/usr/local/etc/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

  db:
    ports:
      - 5432:5432
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    restart: always
    container_name: "proj_web"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  celery:
    build: .
    container_name: "proj_celery"
    command: celery -A proj worker -B
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
