# Generated by Django 3.2.5 on 2021-09-13 11:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import main.utils
import phonenumber_field.modelfields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractBaseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('sold', models.BooleanField(default=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Phone number must be valid'}, max_length=128, null=True, region=None, unique=True, verbose_name='Phone')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('code_inn', models.CharField(default='000000000000', max_length=12, validators=[main.utils.validate_inn], verbose_name='Tax Code')),
                ('img', sorl.thumbnail.fields.ImageField(default='uploads/profile/default.png', upload_to='uploads/profile_pics/')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Phone number must be valid'}, max_length=128, null=True, region=None, unique=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Seller',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('abstractbaselisting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.abstractbaselisting')),
                ('brand_name', models.CharField(max_length=100)),
            ],
            bases=('main.abstractbaselisting',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('abstractbaselisting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.abstractbaselisting')),
                ('used', models.BooleanField(default=True)),
            ],
            bases=('main.abstractbaselisting',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('abstractbaselisting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.abstractbaselisting')),
                ('type_of', models.CharField(max_length=100)),
            ],
            bases=('main.abstractbaselisting',),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_to', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Phone confirmation code')),
                ('response_twillio', models.TextField(blank=True, default='', null=True, verbose_name="Provider's response")),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smslogs', to='main.seller', verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'SMS Journal',
                'verbose_name_plural': 'SMS Journals',
            },
        ),
        migrations.AddField(
            model_name='abstractbaselisting',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing', to='main.category'),
        ),
        migrations.AddField(
            model_name='abstractbaselisting',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing', to='main.seller'),
        ),
        migrations.AddField(
            model_name='abstractbaselisting',
            name='tags',
            field=models.ManyToManyField(related_name='listing', to='main.Tag'),
        ),
        migrations.CreateModel(
            name='ArchiveListing',
            fields=[
            ],
            options={
                'ordering': ['created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.abstractbaselisting',),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', sorl.thumbnail.fields.ImageField(upload_to='uploads/cars/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
    ]
