# Generated by Django 3.2.5 on 2021-08-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Phone confirmation code')),
                ('response_twillio', models.TextField(blank=True, default='', null=True, verbose_name="Provider's response")),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smslogs', to='main.seller', verbose_name='Seller')),
            ],
            options={
                'verbose_name': 'SMS Journal',
                'verbose_name_plural': 'SMS Journals',
            },
        ),
    ]
