# Generated by Django 3.2.5 on 2021-09-16 19:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractbaselisting',
            name='tags',
        ),
        migrations.AddField(
            model_name='abstractbaselisting',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
