# Generated by Django 3.2.5 on 2021-08-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_seller_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='code_inn',
            field=models.CharField(default='', max_length=12, verbose_name='Tax Code'),
        ),
    ]
