# Generated by Django 3.2.5 on 2021-08-30 10:10

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_abstractbaselisting_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='code_inn',
            field=models.CharField(default='000000000000', max_length=12, validators=[main.utils.validate_inn], verbose_name='Tax Code'),
        ),
    ]
