# Generated by Django 3.2.5 on 2021-08-12 15:07

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_seller_code_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='img',
            field=sorl.thumbnail.fields.ImageField(default='uploads/profile/default.png', upload_to='uploads/profile_pics/'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', sorl.thumbnail.fields.ImageField(upload_to='uploads/cars/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
    ]
