# Generated by Django 3.2.5 on 2021-09-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_seller_code_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractbaselisting',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
