# Generated by Django 3.2.5 on 2021-09-09 10:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_seller_code_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Phone number must be valid'}, max_length=128, null=True, region=None, unique=True, verbose_name='Phone'),
        ),
    ]
