# Generated by Django 3.2.5 on 2021-09-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_abstractbaselisting_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractbaselisting',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
