# Generated by Django 3.2.5 on 2021-08-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractbaselisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='abstractbaselisting',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
