# Generated by Django 3.2.5 on 2021-09-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_abstractbaselisting_sold'),
        ('main', '0007_abstractbaselisting_sold'),
    ]

    operations = [
    ]
